### ISSUE TITLE
environment variables

### ISSUE THREAD

**Issue by blvermeu** [ibebbs/SolarEdge.Monitor#1]
hi,

Many thanks for developing and providing this code.
I am currently trying to implement it for my solaredge SE15K however i had some questions with the environment variables that should be included in the initial start of the script:

Solaredge:Monitor:Inverter:Address=[IP Address of the Inverter]
Solaredge:Monitor:MQTT:Address=[IP Address of the MQTT broker]
Solaredge:Monitor:Service:ModelsToRead=inverter

Is my syntax below correct? Do the the ports (device typically 501 and mqtt typically 1883) of the ip addresses need mentioning somewhere?

Thanks for your feedback!

Ben

docker run 
e-Solaredge:Monitor:Inverter:Address=xxx.xxx.xxx.xxx 
e-Solaredge:Monitor:MQTT:Address=xxx.xxx.xxx.xxx
e-Solaredge:Monitor:Service:ModelsToRead=inverter
ibebbs/solaredge.monitor

**Comment by ibebbs** [comment]
Hi Ben,

No problem, I'd love to see this project getting used more. 

So, as shown in the config [here](https://github.com/ibebbs/SolarEdge.Monitor/blob/master/src/SolarEdge.Monitor/Inverter/Config.cs), you can specify the port for the inverter but, if not specified, it defaults to port 502.

Same goes for the MQTT configuration which can be found [here](https://github.com/ibebbs/SolarEdge.Monitor/blob/master/src/SolarEdge.Monitor/Message/Config.cs) and defaults to 1883.
Are you having issues connecting to the inverter/broker?

**Comment by blvermeu** [comment]
Thanks Ian,

Got it working with the following command:

sudo docker run -e Solaredge:Monitor:Inverter:Address=xxx.xxx.xxx.xxx -e Solaredge:Monitor:MQTT:Address=xxx.xxx.xxx.xxx -e Solaredge:Monitor:Service:ModelsToRead=inverter ibebbs/solaredge.monitor

it's reading beautifully into Mosquitto.

my next step will be to automate the start upon systemboot (eg systemd if possible) and then get the data into influxdb and grafana.

Thanks for your help!

kind regards,

Ben

**Comment by ibebbs** [comment]
Great, thanks for letting me know.

Do you have a "modbus meter" attached to your inverter? If so, amending the line `Solaredge:Monitor:Service:ModelsToRead=inverter` to `Solaredge:Monitor:Service:ModelsToRead=inverter,meter` will push a whole bunch more information into MQTT including the current import/export state.

**Comment by blvermeu** [comment]
Hi Ian,

Urm, what do you mean with a "modbus meter"? I only have the SE15K inverter, without any additions to itr, so probably I will not be trying that... ;-)

ps, I read that the connection (tcp) will close after 2 minutes of non-use (no pulling by a script), after which you need to reopen the modbus-tcp on the inverter... have you experienced anything similar to that?

thx!

Ben

**Comment by blvermeu** [comment]
Hi Ian,

Small update, I have managed to get the script working using docker compose, the yml file and systemd. Everything gets publised to the MQTT broker. is there any way of changing the frequency of every 10s? I would like to have data each second. Can this be changed in the yml file?

thanks!

Ben

**Comment by ibebbs** [comment]
Hi Ben,

So [this](https://www.solaredge.com/products/metering-and-sensors/solaredge-modbus-meter#/) is a modbus meter. It connects to your inverter (via the internal RS485 connector - so needs to be professionally fitted) and provides information on production, consumption and import/export.

Once fitted, SolarEdge.Monitor is able to extract "Meter Models" as described on page 17 in [this document](https://www.solaredge.com/sites/default/files/sunspec-implementation-technical-note.pdf).

We use this to import/export monitoring to alert us when we should start using an appliance (i.e. we should start the washing machine when we start exporting energy to the grid).

**Comment by ibebbs** [comment]
With regards to the changing the polling interval, yes, this is also configurable as you can see in [this file](https://github.com/ibebbs/SolarEdge.Monitor/blob/master/src/SolarEdge.Monitor/Service/Config.cs).

Should be as simple as specifying: `Solaredge:Monitor:Service:PollingIntervalSeconds = 1`.

That said **I would strongly recommend against setting the polling interval to 1 second**. I actually tried that when I first developed this system and found that the inverter just didn't have the CPU horse-power to keep up. Not only did it not reply in a timely manner each second but it interrupted the data stream sent to the SolarEdge monitoring platform.

10 seconds seemed to be the most effective polling interval.

**Comment by blvermeu** [comment]
Hi Ian,

Thanks for the feedback. For your information, Indeed I also tried the one second pulling and my feed (and indeed the solaredge monitoring platform) crashed roughly 3 hours after changing that. Meanwhile running it at 10s does not pose a problem.

Kind regards,

Ben

**Comment by ibebbs** [comment]
Glad it's all running well for you. I'll close this issue now.
